// Server
export const SERVER_HOST = `http://localhost:4000`

export const ACCESS_LEVEL_GUEST = 0
export const ACCESS_LEVEL_NORMAL_USER = 1
export const ACCESS_LEVEL_ADMIN = 2

// PayPal
export const SANDBOX_CLIENT_ID = "AaEbKe7EFNBtgRa5svn1ZEJCj5AsMnCHk_Pr53ekN351lXP7MDWQIDFy73kDRKG-W4MY51i4NBxsIplE"
export const PRODUCTION_CLIENT_ID = "TO_MAKE_A_LIVE_REAL_WORLD_APPLICATION_REPLACE_THIS_TEXT_WITH_YOUR_PRODUCTION_CLIENT_ID"